#ifndef _INCLUDED_GRAPHICS_STATUS_H_
#define _INCLUDED_GRAPHICS_STATUS_H_

typedef enum _eGRAPHICS_STATUS
{
	GRAPHICS_STATUS_SUCCESS,
	GRAPHICS_STATUS_INVALID,
	GRAPHICS_STATUS_SURFACE_FINISHED,
	GRAPHICS_STATUS_NO_MEMORY,
	GRAPHICS_STATUS_NULL_POINTER,
	GRAPHICS_STATUS_INVALID_RESTORE,
	GRAPHICS_STATUS_INVALID_POSITION,
	GRAPHICS_STATUS_INVALID_SIZE,
	GRAPHICS_STATUS_INVALID_MATRIX,
	GRAPHICS_STATUS_INVALID_DASH,
	GRAPHICS_STATUS_INVALID_POP_GROUP,
	GRAPHICS_STATUS_INVALID_PATH_DATA,
	GRAPHICS_STATUS_NO_CURRENT_POINT,
	GRAPHICS_STATUS_PATTERN_TYPE_MISMATCH,
	NUM_GRAPHICS_STATUS
} eGRAPHICS_STATUS;

#define GRAPHICS_STATE_DEFAULT_TOLERANCE 0.1

#endif // #ifndef _INCLUDED_GRAPHICS_STATUS_H_
