#include "graphics.h"
#include "graphics_private.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 GraphicsOperatorBoundedByEither(eGRAPHICS_OPERATOR op)
{
	switch(op)
	{
	case GRAPHICS_OPERATOR_OVER:
	case GRAPHICS_OPERATOR_ATOP:
	case GRAPHICS_OPERATOR_DEST:
	case GRAPHICS_OPERATOR_DEST_OVER:
	case GRAPHICS_OPERATOR_DEST_OUT:
	case GRAPHICS_OPERATOR_XOR:
	case GRAPHICS_OPERATOR_ADD:
	case GRAPHICS_OPERATOR_SATURATE:
	case GRAPHICS_OPERATOR_MULTIPLY:
	case GRAPHICS_OPERATOR_SCREEN:
	case GRAPHICS_OPERATOR_OVERLAY:
	case GRAPHICS_OPERATOR_DARKEN:
	case GRAPHICS_OPERATOR_LIGHTEN:
	case GRAPHICS_OPERATOR_COLOR_DODGE:
	case GRAPHICS_OPERATOR_COLOR_BURN:
	case GRAPHICS_OPERATOR_HARD_LIGHT:
	case GRAPHICS_OPERATOR_SOFT_LIGHT:
	case GRAPHICS_OPERATOR_DIFFERENCE:
	case GRAPHICS_OPERATOR_EXCLUSION:
	case GRAPHICS_OPERATOR_HSL_HUE:
	case GRAPHICS_OPERATOR_HSL_SATURATION:
	case GRAPHICS_OPERATOR_HSL_COLOR:
	case GRAPHICS_OPERATOR_HSL_LUMINOSITY:
		return GRAPHICS_OPERATOR_BOUNDED_BY_MASK | GRAPHICS_OPERATOR_BOUNDED_BY_SOURCE;
	case GRAPHICS_OPERATOR_CLEAR:
	case GRAPHICS_OPERATOR_SOURCE:
		return GRAPHICS_OPERATOR_BOUNDED_BY_MASK;
	case GRAPHICS_OPERATOR_OUT:
	case GRAPHICS_OPERATOR_IN:
	case GRAPHICS_OPERATOR_DEST_IN:
	case GRAPHICS_OPERATOR_DEST_ATOP:
		;
	}

	return 0;
}

int GraphicsOperatorBoundedBySource(eGRAPHICS_OPERATOR op)
{
	switch(op)
	{
	case GRAPHICS_OPERATOR_OVER:
	case GRAPHICS_OPERATOR_ATOP:
	case GRAPHICS_OPERATOR_DEST:
	case GRAPHICS_OPERATOR_DEST_OVER:
	case GRAPHICS_OPERATOR_DEST_OUT:
	case GRAPHICS_OPERATOR_XOR:
	case GRAPHICS_OPERATOR_ADD:
	case GRAPHICS_OPERATOR_SATURATE:
	case GRAPHICS_OPERATOR_MULTIPLY:
	case GRAPHICS_OPERATOR_SCREEN:
	case GRAPHICS_OPERATOR_OVERLAY:
	case GRAPHICS_OPERATOR_DARKEN:
	case GRAPHICS_OPERATOR_LIGHTEN:
	case GRAPHICS_OPERATOR_COLOR_DODGE:
	case GRAPHICS_OPERATOR_COLOR_BURN:
	case GRAPHICS_OPERATOR_HARD_LIGHT:
	case GRAPHICS_OPERATOR_SOFT_LIGHT:
	case GRAPHICS_OPERATOR_DIFFERENCE:
	case GRAPHICS_OPERATOR_EXCLUSION:
	case GRAPHICS_OPERATOR_HSL_HUE:
	case GRAPHICS_OPERATOR_HSL_SATURATION:
	case GRAPHICS_OPERATOR_HSL_COLOR:
	case GRAPHICS_OPERATOR_HSL_LUMINOSITY:
		return TRUE;
	case GRAPHICS_OPERATOR_CLEAR:
	case GRAPHICS_OPERATOR_SOURCE:
	case GRAPHICS_OPERATOR_OUT:
	case GRAPHICS_OPERATOR_IN:
	case GRAPHICS_OPERATOR_DEST_IN:
	case GRAPHICS_OPERATOR_DEST_ATOP:
		return FALSE;
	}

	return FALSE;
}

int GraphicsOperatorBoundedByMask(eGRAPHICS_OPERATOR op)
{
	switch(op)
	{
	case GRAPHICS_OPERATOR_CLEAR:
	case GRAPHICS_OPERATOR_SOURCE:
	case GRAPHICS_OPERATOR_OVER:
	case GRAPHICS_OPERATOR_ATOP:
	case GRAPHICS_OPERATOR_DEST:
	case GRAPHICS_OPERATOR_DEST_OVER:
	case GRAPHICS_OPERATOR_DEST_OUT:
	case GRAPHICS_OPERATOR_XOR:
	case GRAPHICS_OPERATOR_ADD:
	case GRAPHICS_OPERATOR_SATURATE:
	case GRAPHICS_OPERATOR_MULTIPLY:
	case GRAPHICS_OPERATOR_SCREEN:
	case GRAPHICS_OPERATOR_OVERLAY:
	case GRAPHICS_OPERATOR_DARKEN:
	case GRAPHICS_OPERATOR_LIGHTEN:
	case GRAPHICS_OPERATOR_COLOR_DODGE:
	case GRAPHICS_OPERATOR_COLOR_BURN:
	case GRAPHICS_OPERATOR_HARD_LIGHT:
	case GRAPHICS_OPERATOR_SOFT_LIGHT:
	case GRAPHICS_OPERATOR_DIFFERENCE:
	case GRAPHICS_OPERATOR_EXCLUSION:
	case GRAPHICS_OPERATOR_HSL_HUE:
	case GRAPHICS_OPERATOR_HSL_SATURATION:
	case GRAPHICS_OPERATOR_HSL_COLOR:
	case GRAPHICS_OPERATOR_HSL_LUMINOSITY:
		return TRUE;
	case GRAPHICS_OPERATOR_OUT:
	case GRAPHICS_OPERATOR_IN:
	case GRAPHICS_OPERATOR_DEST_IN:
	case GRAPHICS_OPERATOR_DEST_ATOP:
		return FALSE;
	}

	return FALSE;
}

#ifdef __cplusplus
}
#endif
