#ifndef _INCLUDED_GRAPHICS_DEFINITIONS_H_
#define _INCLUDED_GRAPHICS_DEFINITIONS_H_

#define GRAPHICS_PATH_BUFFER_SIZE ((512 - sizeof (GRAPHICS_PATH_BUFFER)) \
			   / (2 * sizeof (GRAPHICS_POINT) + sizeof (GRAPHICS_PATH_OPERATOR)))

#endif // #ifndef_INCLUDED_GRAPHICS_DEFINITIONS_H_

