#ifndef _INCLUDED_GRAPHICS_FLAGS_H_
#define _INCLUDED_GRAPHICS_FLAGS_H_

typedef enum _eGRAPHCIS_FLAGS
{
	GRAPHICS_FLAGS_INITED_IMAGE_SPANS_COMPOSITOR = 0x0001
} eGRAPHCIS_FLAGS;

#endif // _INCLUDED_GRAPHICS_FLAGS_H_
