#ifndef _INCLUDED_GUI_ENUM_H_
#define _INCLUDED_GUI_ENUM_H_

typedef enum _eDIALOG_TYPE
{
	DIALOG_TYPE_ERROR,
	DIALOG_TYPE_WARNING
} eDIALOG_TYPE;

typedef enum _eDIALOG_RESULT
{
	DIALOG_RESULT_OK,
	DIALOG_RESULT_CANCEL,
	DIALOG_RESULT_CLOSE
} eDIALOG_RESULT;

#endif  /* #ifndef _INCLUDED_GUI_ENUM_H_ */
