#ifndef _INCLUDED_PIXEL_MANIPULATE_OPERATOR_H_
#define _INCLUDED_PIXEL_MANIPULATE_OPERATOR_H_

typedef enum _ePIXEL_MANIPULATE_OPERATE
{
	PIXEL_MANIPULATE_OPERATE_CLEAR			= 0x00,
	PIXEL_MANIPULATE_OPERATE_SRC			= 0x01,
	PIXEL_MANIPULATE_OPERATE_DST			= 0x02,
	PIXEL_MANIPULATE_OPERATE_OVER			= 0x03,
	PIXEL_MANIPULATE_OPERATE_OVER_REVERSE   = 0x04,
	PIXEL_MANIPULATE_OPERATE_IN			 = 0x05,
	PIXEL_MANIPULATE_OPERATE_IN_REVERSE		= 0x06,
	PIXEL_MANIPULATE_OPERATE_OUT			= 0x07,
	PIXEL_MANIPULATE_OPERATE_OUT_REVERSE	= 0x08,
	PIXEL_MANIPULATE_OPERATE_ATOP			= 0x09,
	PIXEL_MANIPULATE_OPERATE_ATOP_REVERSE	= 0x0a,
	PIXEL_MANIPULATE_OPERATE_XOR			= 0x0b,
	PIXEL_MANIPULATE_OPERATE_ADD			= 0x0c,
	PIXEL_MANIPULATE_OPERATE_SATURATE		= 0x0d,

	PIXEL_MANIPULATE_OPERATE_DISJOINT_CLEAR		 = 0x10,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_SRC		   = 0x11,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_DST		   = 0x12,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_OVER		  = 0x13,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_OVER_REVERSE	= 0x14,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_IN			= 0x15,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_IN_REVERSE	= 0x16,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_OUT		   = 0x17,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_OUT_REVERSE	= 0x18,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_ATOP	  	= 0x19,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_ATOP_REVERSE	= 0x1a,
	PIXEL_MANIPULATE_OPERATE_DISJOINT_XOR	   	= 0x1b,

	PIXEL_MANIPULATE_OPERATE_CONJOINT_CLEAR 		= 0x20,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_SRC   		= 0x21,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_DST   		= 0x22,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_OVER  		= 0x23,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_OVER_REVERSE	= 0x24,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_IN			= 0x25,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_IN_REVERSE	= 0x26,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_OUT   		= 0x27,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_OUT_REVERSE	= 0x28,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_ATOP  		= 0x29,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_ATOP_REVERSE	= 0x2a,
	PIXEL_MANIPULATE_OPERATE_CONJOINT_XOR   		= 0x2b,

	PIXEL_MANIPULATE_OPERATE_MULTIPLY		   = 0x30,
	PIXEL_MANIPULATE_OPERATE_SCREEN			 = 0x31,
	PIXEL_MANIPULATE_OPERATE_OVERLAY			= 0x32,
	PIXEL_MANIPULATE_OPERATE_DARKEN			 = 0x33,
	PIXEL_MANIPULATE_OPERATE_LIGHTEN			= 0x34,
	PIXEL_MANIPULATE_OPERATE_COLOR_DODGE		= 0x35,
	PIXEL_MANIPULATE_OPERATE_COLOR_BURN		  = 0x36,
	PIXEL_MANIPULATE_OPERATE_HARD_LIGHT		 = 0x37,
	PIXEL_MANIPULATE_OPERATE_SOFT_LIGHT		 = 0x38,
	PIXEL_MANIPULATE_OPERATE_DIFFERENCE		 = 0x39,
	PIXEL_MANIPULATE_OPERATE_EXCLUSION		  = 0x3a,
	PIXEL_MANIPULATE_OPERATE_HSL_HUE			= 0x3b,
	PIXEL_MANIPULATE_OPERATE_HSL_SATURATION		= 0x3c,
	PIXEL_MANIPULATE_OPERATE_HSL_COLOR			= 0x3d,
	PIXEL_MANIPULATE_OPERATE_HSL_LUMINOSITY		= 0x3e,

	PIXEL_MANIPULATE_NUM_OPERATORS,
	PIXEL_MANIPULATE_OPERATE_NONE = PIXEL_MANIPULATE_NUM_OPERATORS,
	PIXEL_MANIPULATE_OPERATE_ANY
} ePIXEL_MANIPULATE_OPERATE;

#endif // #ifndef _INCLUDED_PIXEL_MANIPULATE_OPERATOR_H_
