#ifndef _INCLUDED_PIXEL_MANIPULATE_FORMAT_H_
#define _INCLUDED_PIXEL_MANIPULATE_FORMAT_H_

#define PIXEL_MANIPULATE_FORMAT(bpp, type, a, r, g, b) (((bpp) << 24) | \
	((type) << 16) | \
	((a) << 12) | \
	((r) << 8) | \
	((g) << 4) | \
	((b)))

#define PIXEL_MANIPULATE_TYPE_A 1
#define PIXEL_MANIPULATE_TYPE_ARGB 2
#define PIXEL_MANIPULATE_TYPE_ABGR 3
#define PIXEL_MANIPULATE_TYPE_COLOR 4
#define PIXEL_MANIPULATE_TYPE_GRAY 5
#define PIXEL_MANIPULATE_TYPE_BGRA 8
#define PIXEL_MANIPULATE_TYPE_RGBA 9
#define PIXEL_MANIPULATE_TYPE_SRGB 10
#define PIXEL_MANIPULATE_FORMAT_TYPE(f)	(((f) >> 16) & 0x3f)

typedef enum _ePIXEL_MANIPULATE_FORMAT
{
	PIXEL_MANIPULATE_FORMAT_A8R8G8B8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_ARGB, 8, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_X8R8G8B8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_ARGB, 0, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_A8B8G8R8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_ABGR, 8, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_X8B8G8R8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_ABGR, 0, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_B8G8R8A8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_BGRA, 8, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_B8G8R8X8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_BGRA, 0, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_R8G8B8A8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_RGBA, 8, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_R8G8B8X8 = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_RGBA, 0, 8, 8, 8),
	PIXEL_MANIPULATE_FORAMT_R8G8B8 = PIXEL_MANIPULATE_FORMAT(24, PIXEL_MANIPULATE_TYPE_RGBA, 0, 8, 8, 8),
	PIXEL_MANIPULATE_FORMAT_A8 = PIXEL_MANIPULATE_FORMAT(8, PIXEL_MANIPULATE_TYPE_A, 8, 0, 0, 0),
	PIXEL_MANIPULATE_FORMAT_A1 = PIXEL_MANIPULATE_FORMAT(1, PIXEL_MANIPULATE_TYPE_A, 1, 0, 0, 0),
	NUM_PIXEL_MANIPULATE_FORMAT = PIXEL_MANIPULATE_FORMAT(32, PIXEL_MANIPULATE_TYPE_ARGB, 8, 8, 8, 8) + 1,
	PIXEL_MANIPULATE_FORMAT_INVALID = -1,
	PIXEL_MANIPULATE_FORMAT_NULL = 0,
	PIXEL_MANIPULATE_FORMAT_BUFFER = PIXEL_MANIPULATE_FORMAT(0, 2, 0, 0, 0, 0),
	PIXEL_MANIPULATE_FORMAT_R_BUFFER = PIXEL_MANIPULATE_FORMAT(0, 3, 0, 0, 0, 0),
	PIXEL_MANIPULATE_FORMAT_UNKOWN = PIXEL_MANIPULATE_FORMAT(0, 4, 0, 0, 0, 0),
	PIXEL_MANIPULATE_FORMAT_ANY = PIXEL_MANIPULATE_FORMAT(0, 5, 0, 0, 0, 0),

	PIXEL_MANIPULATE_FORMAT_R5G6B5 = PIXEL_MANIPULATE_FORMAT(16, PIXEL_MANIPULATE_TYPE_ARGB, 0, 5, 6, 5),
	PIXEL_MANIPULATE_FORMAT_B5G6R5 = PIXEL_MANIPULATE_FORMAT(16, PIXEL_MANIPULATE_TYPE_ABGR, 0, 5, 6, 5)
} ePIXEL_MANIPULATE_FORMAT;

#define PIXEL_MANIPULATE_FORMAT_RESHIFT(val, ofs, num) \
	(((val >> (ofs)) & ((1 << (num)) - 1)) << ((val >> 22) & 3))

#define PIXEL_MANIPULATE_FORMAT_A(f)	PIXEL_MANIPULATE_FORMAT_RESHIFT(f, 12, 4)
#define PIXEL_MANIPULATE_FORMAT_R(f)	PIXEL_MANIPULATE_FORMAT_RESHIFT(f, 8, 4)
#define PIXEL_MANIPULATE_FORMAT_G(f)	PIXEL_MANIPULATE_FORMAT_RESHIFT(f, 4, 4)
#define PIXEL_MANIPULATE_FORMAT_B(f)	PIXEL_MANIPULATE_FORMAT_RESHIFT(f, 0, 4)

#define PIXEL_MANIPULATE_RESHIFT(value, offset, num) (((value >> (offset)) & ((1 << (num)) - 1)) << ((value >> 22) & 3))
#define PIXEL_MANIPULATE_BIT_PER_PIXEL(FORMAT) PIXEL_MANIPULATE_RESHIFT(FORMAT, 24, 8)

#endif // #ifndef _INCLUDED_PIXEL_MANIPULATE_FORMAT_H_

